// src/LinguaCoach.Web/src/app/features/admin/create-student/create-student.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AdminService } from '../../../core/services/admin.service';
import { AuthService } from '../../../core/services/auth.service';
import { ToastService } from '../../../core/services/toast.service';
import {
  SpAdminAlertComponent,
  SpAdminButtonComponent,
  SpAdminCardComponent,
  SpAdminFormFieldComponent,
  SpAdminInputComponent,
  SpAdminPageBodyComponent,
  SpAdminPageHeaderComponent,
} from '../../../design-system/admin';

@Component({
  selector: 'app-create-student',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    RouterLink,
    SpAdminAlertComponent,
    SpAdminButtonComponent,
    SpAdminCardComponent,
    SpAdminFormFieldComponent,
    SpAdminInputComponent,
    SpAdminPageBodyComponent,
    SpAdminPageHeaderComponent,
  ],
  templateUrl: './create-student.component.html',
  styles: [`
    .sp-cs-layout {
      display: grid;
      gap: 24px;
    }
    @media(min-width: 1100px) {
      .sp-cs-layout {
        grid-template-columns: 1fr 300px;
        align-items: start;
      }
    }

    .sp-cs-section {
      background: var(--sp-admin-surface, #fff);
      border: 1px solid var(--sp-admin-border, #ECE9F5);
      border-radius: 16px;
      padding: 24px;
      margin-bottom: 16px;
      display: flex;
      flex-direction: column;
      gap: 16px;
    }

    .sp-cs-section-header { display: flex; flex-direction: column; gap: 4px; }
    .sp-cs-section-title {
      font-size: 15px;
      font-weight: 800;
      color: var(--sp-admin-text, #0F172A);
      display: flex;
      align-items: center;
      gap: 8px;
    }
    .sp-cs-section-sub { font-size: 13px; color: var(--sp-admin-text-muted, #64748B); }

    .sp-cs-optional-badge {
      font-size: 10px;
      font-weight: 700;
      letter-spacing: .06em;
      text-transform: uppercase;
      background: var(--sp-admin-primary-bg, #EDEBFF);
      color: var(--sp-admin-primary, #5B4BE8);
      padding: 2px 7px;
      border-radius: 99px;
    }

    .sp-cs-toggle-row {
      display: flex;
      align-items: flex-start;
      gap: 12px;
      border-radius: 12px;
      border: 1px solid var(--sp-admin-border, #ECE9F5);
      background: var(--sp-admin-surface-subtle, #FBFAFE);
      padding: 12px;
    }
    .sp-cs-toggle-checkbox {
      margin-top: 2px;
      width: 16px;
      height: 16px;
      accent-color: var(--sp-admin-primary, #5B4BE8);
      flex-shrink: 0;
      cursor: pointer;
    }
    .sp-cs-toggle-label {
      font-size: 13.5px;
      font-weight: 600;
      color: var(--sp-admin-text, #0F172A);
      cursor: pointer;
    }
    .sp-cs-toggle-hint {
      margin: 2px 0 0;
      font-size: 12px;
      color: var(--sp-admin-text-muted, #64748B);
    }

    .sp-cs-security-note {
      display: flex;
      align-items: flex-start;
      gap: 8px;
      font-size: 12px;
      color: #475569;
      background: #fffbeb;
      border: 1px solid #fde68a;
      border-radius: 10px;
      padding: 10px 12px;
    }

    .sp-cs-toggle-btn {
      display: flex;
      align-items: center;
      justify-content: space-between;
      font-size: 13.5px;
      font-weight: 600;
      color: var(--sp-admin-primary, #5B4BE8);
      background: none;
      border: none;
      cursor: pointer;
      padding: 0;
      width: 100%;
    }
    .sp-cs-toggle-chevron {
      width: 16px;
      height: 16px;
      transition: transform .2s;
    }
    .sp-cs-toggle-chevron--open { transform: rotate(180deg); }

    .sp-cs-optional-fields {
      display: flex;
      flex-direction: column;
      gap: 14px;
      border-radius: 12px;
      border: 1px solid var(--sp-admin-border, #ECE9F5);
      background: var(--sp-admin-surface-subtle, #FBFAFE);
      padding: 16px;
    }

    .sp-cs-two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
    @media(max-width: 600px) { .sp-cs-two-col { grid-template-columns: 1fr; } }

    .sp-cs-native-select {
      width: 100%;
      border: 1px solid var(--sp-admin-border, #ECE9F5);
      border-radius: 8px;
      padding: 8px 12px;
      font-size: 13.5px;
      color: var(--sp-admin-text, #0F172A);
      background: #fff;
    }

    .sp-cs-actions {
      display: flex;
      align-items: center;
      justify-content: flex-end;
      gap: 12px;
      padding-top: 4px;
    }

    /* Aside panel */
    .sp-cs-aside-card {
      background: var(--sp-admin-surface, #fff);
      border: 1px solid var(--sp-admin-border, #ECE9F5);
      border-radius: 16px;
      padding: 20px;
      position: sticky;
      top: 24px;
    }
    .sp-cs-aside-title {
      font-size: 13px;
      font-weight: 800;
      color: var(--sp-admin-text, #0F172A);
      text-transform: uppercase;
      letter-spacing: .06em;
      margin-bottom: 16px;
    }
    .sp-cs-aside-steps {
      list-style: none;
      margin: 0;
      padding: 0;
      display: flex;
      flex-direction: column;
      gap: 14px;
    }
    .sp-cs-aside-steps li {
      display: flex;
      align-items: flex-start;
      gap: 12px;
    }
    .sp-cs-step-dot {
      width: 24px;
      height: 24px;
      border-radius: 50%;
      background: var(--sp-admin-primary-bg, #EDEBFF);
      color: var(--sp-admin-primary, #5B4BE8);
      font-size: 11px;
      font-weight: 800;
      display: flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
    }
    .sp-cs-step-dot--done {
      background: var(--sp-admin-green-bg, #dcfce7);
      color: var(--sp-admin-green, #16a34a);
    }
    .sp-cs-step-label { font-size: 13px; font-weight: 700; color: var(--sp-admin-text, #0F172A); }
    .sp-cs-step-desc { font-size: 12px; color: var(--sp-admin-text-muted, #64748B); margin-top: 2px; }

    .sp-cs-aside-note {
      margin-top: 16px;
      font-size: 11.5px;
      color: #94a3b8;
      font-style: italic;
      border-top: 1px solid var(--sp-admin-border, #ECE9F5);
      padding-top: 12px;
    }
  `],
})
export class CreateStudentComponent {
  // Required fields
  email = '';
  temporaryPassword = '';
  mustChangePassword = true;

  // Optional profile fields
  showOptional = false;
  firstName = '';
  lastName = '';
  displayName = '';
  careerContext = '';
  learningGoal = '';
  preferredSessionDurationMinutes: number | null = null;
  professionalExperienceLevel: number | null = null;
  roleFamiliarity: number | null = null;

  loading = signal(false);
  error = signal('');
  success = signal('');
  emailError = signal('');
  passwordError = signal('');

  readonly experienceLevels = [
    { value: 0, label: 'Entry level' },
    { value: 1, label: 'Mid-level' },
    { value: 2, label: 'Senior' },
    { value: 3, label: 'Lead / Principal' },
  ];

  readonly familiarityLevels = [
    { value: 0, label: 'New to role' },
    { value: 1, label: 'Familiar' },
    { value: 2, label: 'Very experienced' },
  ];

  readonly sessionDurations = [15, 20, 30, 45, 60];

  constructor(
    private adminService: AdminService,
    public auth: AuthService,
    private router: Router,
    private toast: ToastService) {}

  onSubmit(): void {
    if (!this.validate()) return;

    this.loading.set(true);
    this.error.set('');
    this.success.set('');

    const request: Parameters<AdminService['createStudent']>[0] = {
      email: this.email.trim(),
      temporaryPassword: this.temporaryPassword,
      mustChangePassword: this.mustChangePassword,
    };

    if (this.showOptional) {
      if (this.firstName.trim()) request.firstName = this.firstName.trim();
      if (this.lastName.trim()) request.lastName = this.lastName.trim();
      if (this.displayName.trim()) request.displayName = this.displayName.trim();
      if (this.careerContext.trim()) request.careerContext = this.careerContext.trim();
      if (this.learningGoal.trim()) request.learningGoal = this.learningGoal.trim();
      if (this.preferredSessionDurationMinutes) request.preferredSessionDurationMinutes = this.preferredSessionDurationMinutes;
      if (this.professionalExperienceLevel !== null) request.professionalExperienceLevel = this.professionalExperienceLevel;
      if (this.roleFamiliarity !== null) request.roleFamiliarity = this.roleFamiliarity;
    }

    this.adminService.createStudent(request).subscribe({
      next: () => {
        this.loading.set(false);
        this.toast.success('Student created successfully');
        this.router.navigate(['/admin/students']);
      },
      error: err => {
        this.loading.set(false);
        if (err.status === 409) {
          this.error.set('A student with this email already exists.');
        } else {
          this.error.set(err.error?.error ?? 'Failed to create student.');
        }
      },
    });
  }

  startAnother(): void {
    this.email = '';
    this.temporaryPassword = '';
    this.mustChangePassword = true;
    this.showOptional = false;
    this.firstName = '';
    this.lastName = '';
    this.displayName = '';
    this.careerContext = '';
    this.learningGoal = '';
    this.preferredSessionDurationMinutes = null;
    this.professionalExperienceLevel = null;
    this.roleFamiliarity = null;
    this.success.set('');
    this.error.set('');
    this.emailError.set('');
    this.passwordError.set('');
  }

  private validate(): boolean {
    this.emailError.set('');
    this.passwordError.set('');
    const email = this.email.trim();
    if (!email) {
      this.emailError.set('Enter the student email address.');
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      this.emailError.set('Enter a valid email address.');
    }

    if (!this.temporaryPassword) {
      this.passwordError.set('Enter a temporary password.');
    } else if (this.temporaryPassword.length < 8) {
      this.passwordError.set('Use at least 8 characters.');
    } else if (!/\d/.test(this.temporaryPassword)) {
      this.passwordError.set('Include at least one number.');
    }

    return !this.emailError() && !this.passwordError();
  }
}

<sp-admin-page-header title="Create student" subtitle="Add a new pilot account to the SpeakPath platform">
  <sp-admin-button variant="ghost" routerLink="/admin/students">← Back to Students</sp-admin-button>
</sp-admin-page-header>

<sp-admin-page-body>
<div class="sp-cs-layout">

  <!-- Left: form sections -->
  <div class="sp-cs-main">

    @if (error()) {
      <sp-admin-alert variant="error">{{ error() }}</sp-admin-alert>
    }

    <form (ngSubmit)="onSubmit()" novalidate>

      <!-- Section 1: Account credentials -->
      <div class="sp-cs-section">
        <div class="sp-cs-section-header">
          <div class="sp-cs-section-title">Account credentials</div>
          <div class="sp-cs-section-sub">The student uses these to log in. They will be prompted to set a new password on first login.</div>
        </div>

        <sp-admin-form-field label="Student email" [error]="emailError()">
          <sp-admin-input
            id="studentEmail"
            type="email"
            [(ngModel)]="email"
            name="email"
            [required]="true"
            placeholder="student@example.com" />
        </sp-admin-form-field>

        <sp-admin-form-field label="Temporary password" hint="Min 10 characters — upper, lower, digit, and special character." [error]="passwordError()">
          <sp-admin-input
            id="temporaryPassword"
            type="text"
            [(ngModel)]="temporaryPassword"
            name="password"
            [required]="true"
            placeholder="e.g. Pilot2025!" />
        </sp-admin-form-field>

        <!-- Must-change-password toggle -->
        <div class="sp-cs-toggle-row">
          <input
            id="mustChangePassword"
            type="checkbox"
            [(ngModel)]="mustChangePassword"
            name="mustChangePassword"
            class="sp-cs-toggle-checkbox"
          />
          <div>
            <label for="mustChangePassword" class="sp-cs-toggle-label">Require password change on first login</label>
            <p class="sp-cs-toggle-hint">Recommended for real students. Disable only for test accounts.</p>
          </div>
        </div>

        <!-- Security note -->
        <div class="sp-cs-security-note">
          <svg width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" style="flex-shrink:0;margin-top:1px"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>
          <span>The temporary password is shown once — save it before sharing with the student. The student must sign in and set their own password before starting onboarding.</span>
        </div>

      </div>

      <!-- Section 2: Student profile (optional) -->
      <div class="sp-cs-section">
        <div class="sp-cs-section-header">
          <div class="sp-cs-section-title">
            Student profile
            <span class="sp-cs-optional-badge">Optional</span>
          </div>
          <div class="sp-cs-section-sub">Pre-filling these fields skips the matching onboarding steps and takes the student directly to placement.</div>
        </div>

        <button
          type="button"
          class="sp-cs-toggle-btn"
          (click)="showOptional = !showOptional"
        >
          <span>{{ showOptional ? 'Hide profile fields' : 'Add profile fields' }}</span>
          <svg class="sp-cs-toggle-chevron" [class.sp-cs-toggle-chevron--open]="showOptional"
            fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/>
          </svg>
        </button>

        @if (showOptional) {
          <div class="sp-cs-optional-fields">

            <div class="sp-cs-two-col">
              <sp-admin-form-field label="First name">
                <sp-admin-input id="firstName" type="text" [(ngModel)]="firstName" name="firstName" placeholder="Ehsan" />
              </sp-admin-form-field>
              <sp-admin-form-field label="Last name">
                <sp-admin-input id="lastName" type="text" [(ngModel)]="lastName" name="lastName" placeholder="Aliverdi" />
              </sp-admin-form-field>
            </div>

            <sp-admin-form-field label="Display name" hint="What the student goes by in the platform">
              <sp-admin-input id="displayName" type="text" [(ngModel)]="displayName" name="displayName" placeholder="e.g. Alice" />
            </sp-admin-form-field>

            <sp-admin-form-field label="Career context">
              <sp-admin-input id="careerContext" type="text" [(ngModel)]="careerContext" name="careerContext" placeholder="e.g. Software engineering, Healthcare" />
            </sp-admin-form-field>

            <sp-admin-form-field label="Learning goal">
              <sp-admin-input id="learningGoal" type="text" [(ngModel)]="learningGoal" name="learningGoal" placeholder="e.g. Communicate confidently in meetings" />
            </sp-admin-form-field>

            <sp-admin-form-field label="Preferred session duration">
              <select id="sessionDuration" [(ngModel)]="preferredSessionDurationMinutes" name="sessionDuration" class="sp-cs-native-select">
                <option [ngValue]="null">Not specified</option>
                @for (d of sessionDurations; track d) {
                  <option [ngValue]="d">{{ d }} minutes</option>
                }
              </select>
            </sp-admin-form-field>

            <div class="sp-cs-two-col">
              <sp-admin-form-field label="Experience level">
                <select id="experienceLevel" [(ngModel)]="professionalExperienceLevel" name="experienceLevel" class="sp-cs-native-select">
                  <option [ngValue]="null">Not specified</option>
                  @for (l of experienceLevels; track l.value) {
                    <option [ngValue]="l.value">{{ l.label }}</option>
                  }
                </select>
              </sp-admin-form-field>
              <sp-admin-form-field label="Role familiarity">
                <select id="roleFamiliarity" [(ngModel)]="roleFamiliarity" name="roleFamiliarity" class="sp-cs-native-select">
                  <option [ngValue]="null">Not specified</option>
                  @for (f of familiarityLevels; track f.value) {
                    <option [ngValue]="f.value">{{ f.label }}</option>
                  }
                </select>
              </sp-admin-form-field>
            </div>

          </div>
        }

      </div>

      <!-- Section 3: Actions -->
      <div class="sp-cs-actions">
        <sp-admin-button variant="ghost" type="button" routerLink="/admin/students">Cancel</sp-admin-button>
        <sp-admin-button type="submit" [disabled]="loading()" [loading]="loading()">
          {{ loading() ? 'Creating...' : 'Create student' }}
        </sp-admin-button>
      </div>

    </form>
  </div>

  <!-- Right: what happens next panel -->
  <aside class="sp-cs-aside">
    <div class="sp-cs-aside-card">
      <div class="sp-cs-aside-title">What happens next</div>
      <ol class="sp-cs-aside-steps">
        <li>
          <div class="sp-cs-step-dot sp-cs-step-dot--done">1</div>
          <div>
            <div class="sp-cs-step-label">Account created</div>
            <div class="sp-cs-step-desc">Student email and temp password saved.</div>
          </div>
        </li>
        <li>
          <div class="sp-cs-step-dot">2</div>
          <div>
            <div class="sp-cs-step-label">Student signs in</div>
            <div class="sp-cs-step-desc">Uses the temporary password once.</div>
          </div>
        </li>
        <li>
          <div class="sp-cs-step-dot">3</div>
          <div>
            <div class="sp-cs-step-label">Password change</div>
            <div class="sp-cs-step-desc">Sets their own secure password before onboarding.</div>
          </div>
        </li>
        <li>
          <div class="sp-cs-step-dot">4</div>
          <div>
            <div class="sp-cs-step-label">Onboarding</div>
            <div class="sp-cs-step-desc">Completes profile and goals (skipped fields auto-pre-filled).</div>
          </div>
        </li>
        <li>
          <div class="sp-cs-step-dot">5</div>
          <div>
            <div class="sp-cs-step-label">Placement test</div>
            <div class="sp-cs-step-desc">CEFR level determined. Learning path unlocks.</div>
          </div>
        </li>
      </ol>

      <div class="sp-cs-aside-note">
        Welcome email: backend not available yet — no automated email send endpoint.
        Share the temporary password manually.
      </div>
    </div>
  </aside>

</div>
</sp-admin-page-body>

// docs/design/speakpath/admin/pages/create-student.jsx
// SpeakPath Admin — Create Student (production SaaS redesign)
(function () {
  const { useState } = React;
  const { AIcon } = window;

  function Toggle({ on, onChange, label, sub }) {
    return (
      <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between',
        padding:'13px 0', borderBottom:'1px solid var(--border)' }}>
        <div>
          <div style={{ fontSize:13.5, fontWeight:600, color:'var(--ink)' }}>{label}</div>
          {sub && <div style={{ fontSize:12, color:'var(--muted)', marginTop:2 }}>{sub}</div>}
        </div>
        <button
          onClick={() => onChange(!on)}
          style={{
            width:40, height:23, borderRadius:99, border:'none', cursor:'pointer',
            position:'relative', padding:0, flexShrink:0,
            background: on ? '#5B4BE8' : '#DDD9EC',
            transition:'background .18s',
          }}>
          <span style={{
            position:'absolute', top:3, left: on ? 20 : 3,
            width:17, height:17, borderRadius:'50%',
            background:'#fff', boxShadow:'0 1px 3px rgba(0,0,0,.15)',
            transition:'left .18s',
          }}/>
        </button>
      </div>
    );
  }

  function FormSection({ title, sub, children }) {
    return (
      <div className="adm-card adm-card-p" style={{ marginBottom:16 }}>
        <div style={{ marginBottom:20 }}>
          <div style={{ fontSize:14.5, fontWeight:800, color:'var(--ink)' }}>{title}</div>
          {sub && <div style={{ fontSize:13, color:'var(--muted)', marginTop:3 }}>{sub}</div>}
        </div>
        {children}
      </div>
    );
  }

  function Field({ label, hint, required, children, half }) {
    return (
      <div style={{ display:'flex', flexDirection:'column', gap:6, flex: half ? '1 1 calc(50% - 8px)' : '1 1 100%' }}>
        <label style={{ fontSize:13, fontWeight:700, color:'var(--ink)', display:'flex', gap:4, alignItems:'center' }}>
          {label}
          {required && <span style={{ color:'#EF4444', fontSize:13 }}>*</span>}
        </label>
        {children}
        {hint && <span style={{ fontSize:12, color:'var(--muted)' }}>{hint}</span>}
      </div>
    );
  }

  function AdminCreateStudent({ navigate }) {
    // Account
    const [email, setEmail]         = useState('');
    const [password, setPassword]   = useState('');
    const [showPw, setShowPw]       = useState(false);
    const [requireChg, setRequireChg] = useState(true);
    const [sendEmail, setSendEmail] = useState(true);

    // Profile
    const [displayName, setDisplayName] = useState('');
    const [jobTitle, setJobTitle]       = useState('');
    const [industry, setIndustry]       = useState('');
    const [company, setCompany]         = useState('');
    const [yearsExp, setYearsExp]       = useState('');

    // Learning context
    const [nativeLang, setNativeLang]   = useState('');
    const [knownLevel, setKnownLevel]   = useState('');
    const [goal, setGoal]               = useState('');
    const [weeklyGoal, setWeeklyGoal]   = useState('3');

    // Admin
    const [notes, setNotes]             = useState('');
    const [lifecycle, setLifecycle]     = useState('Onboarding required');
    const [cohort, setCohort]           = useState('');

    const [errors, setErrors]   = useState({});
    const [submitted, setSubmitted] = useState(false);

    function validate() {
      const errs = {};
      if (!email) errs.email = 'Email is required';
      else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) errs.email = 'Enter a valid email address';
      if (!password) errs.password = 'Temporary password is required';
      else if (password.length < 8) errs.password = 'Minimum 8 characters';
      else if (!/\d/.test(password)) errs.password = 'Must include at least one number';
      return errs;
    }

    function handleSubmit(e) {
      e.preventDefault();
      const errs = validate();
      setErrors(errs);
      if (Object.keys(errs).length > 0) return;
      setSubmitted(true);
      setTimeout(() => navigate('students'), 1800);
    }

    if (submitted) {
      return (
        <div style={{ maxWidth:520, margin:'80px auto', textAlign:'center', padding:'0 20px' }}>
          <div style={{ width:64, height:64, borderRadius:16, background:'#E0F6EE',
            display:'grid', placeItems:'center', margin:'0 auto 20px' }}>
            <AIcon n="check" s={28} c="#13B07C" w={2.5}/>
          </div>
          <div style={{ fontSize:22, fontWeight:800, color:'var(--ink)', marginBottom:8 }}>Student created</div>
          <div style={{ fontSize:14, color:'var(--muted)', lineHeight:1.6 }}>
            {email} has been added to the pilot cohort.{sendEmail ? ' A welcome email is on its way.' : ''} Redirecting to student list…
          </div>
        </div>
      );
    }

    return (
      <div>
        <div style={{ marginBottom:24 }}>
          <button className="adm-btn adm-btn-ghost adm-btn-sm" onClick={() => navigate('students')}
            style={{ marginBottom:16 }}>
            <AIcon n="arrowLeft" s={14}/>Back to Students
          </button>
          <h1 style={{ fontSize:24, fontWeight:800, color:'var(--ink)', letterSpacing:'-.035em' }}>Create student</h1>
          <p style={{ fontSize:13, color:'var(--muted)', marginTop:4 }}>Add a new pilot account to the SpeakPath platform</p>
        </div>

        <form onSubmit={handleSubmit} noValidate>
          <div style={{ display:'grid', gridTemplateColumns:'1fr 300px', gap:20, alignItems:'start' }}>
            {/* ── LEFT: form sections ── */}
            <div>

              {/* 1. Account credentials */}
              <FormSection title="Account credentials"
                sub="The student will use these to log in. They'll be prompted to change their password on first login.">
                <div style={{ display:'flex', flexWrap:'wrap', gap:16, marginBottom:16 }}>
                  <Field label="Student email" required>
                    <input className="adm-input" type="email" placeholder="student@company.com"
                      value={email} onChange={e => { setEmail(e.target.value); setErrors(x => ({...x, email:null})); }}
                      style={{ borderColor: errors.email ? '#EF4444' : undefined }}/>
                    {errors.email && <span style={{ fontSize:12, color:'#EF4444' }}>{errors.email}</span>}
                  </Field>
                </div>
                <div style={{ display:'flex', flexWrap:'wrap', gap:16, marginBottom:4 }}>
                  <Field label="Temporary password" required
                    hint="Min 8 characters, at least one number">
                    <div style={{ position:'relative' }}>
                      <input className="adm-input" type={showPw ? 'text' : 'password'}
                        placeholder="Min 8 characters, include a number"
                        value={password} onChange={e => { setPassword(e.target.value); setErrors(x => ({...x, password:null})); }}
                        style={{ borderColor: errors.password ? '#EF4444' : undefined, paddingRight:40 }}/>
                      <button type="button" onClick={() => setShowPw(v => !v)}
                        style={{ position:'absolute', right:10, top:'50%', transform:'translateY(-50%)',
                          background:'none', border:'none', cursor:'pointer', color:'var(--muted)', padding:0 }}>
                        <AIcon n="eye" s={16} c="currentColor"/>
                      </button>
                    </div>
                    {errors.password && <span style={{ fontSize:12, color:'#EF4444' }}>{errors.password}</span>}
                  </Field>
                </div>
                <div style={{ borderTop:'1px solid var(--border)', marginTop:16 }}>
                  <Toggle on={requireChg} onChange={setRequireChg}
                    label="Require password change on first login"
                    sub="Recommended for real students. Disable for test accounts."/>
                  <Toggle on={sendEmail} onChange={setSendEmail}
                    label="Send welcome email"
                    sub="Sends login link and onboarding instructions to the student."/>
                </div>
              </FormSection>

              {/* 2. Student profile */}
              <FormSection title="Student profile"
                sub="Profile information helps personalise the learning path. Pre-filling these fields skips the corresponding onboarding steps.">
                <div style={{ display:'flex', flexWrap:'wrap', gap:16, marginBottom:16 }}>
                  <Field label="Display name" half>
                    <input className="adm-input" placeholder="e.g. Alice Nguyen"
                      value={displayName} onChange={e => setDisplayName(e.target.value)}/>
                  </Field>
                  <Field label="Job title" half>
                    <input className="adm-input" placeholder="e.g. Senior Engineer"
                      value={jobTitle} onChange={e => setJobTitle(e.target.value)}/>
                  </Field>
                </div>
                <div style={{ display:'flex', flexWrap:'wrap', gap:16, marginBottom:16 }}>
                  <Field label="Industry" half>
                    <select className="adm-select" style={{ width:'100%' }} value={industry} onChange={e => setIndustry(e.target.value)}>
                      <option value="">Select industry</option>
                      {['Technology','Finance & Fintech','Healthcare','Legal','Education','Marketing & Media','Retail & E-commerce','Engineering','Other'].map(o => <option key={o}>{o}</option>)}
                    </select>
                  </Field>
                  <Field label="Company" half>
                    <input className="adm-input" placeholder="e.g. Acme Corp"
                      value={company} onChange={e => setCompany(e.target.value)}/>
                  </Field>
                </div>
                <div style={{ display:'flex', flexWrap:'wrap', gap:16 }}>
                  <Field label="Years of work experience" half>
                    <select className="adm-select" style={{ width:'100%' }} value={yearsExp} onChange={e => setYearsExp(e.target.value)}>
                      <option value="">Not specified</option>
                      <option>0–1 years (early career)</option>
                      <option>2–5 years (junior–mid)</option>
                      <option>6–10 years (mid–senior)</option>
                      <option>10+ years (senior–lead)</option>
                    </select>
                  </Field>
                </div>
              </FormSection>

              {/* 3. Learning context */}
              <FormSection title="Learning context"
                sub="Used to personalise exercises and set the right CEFR baseline. Leave blank to let the student complete the placement assessment.">
                <div style={{ display:'flex', flexWrap:'wrap', gap:16, marginBottom:16 }}>
                  <Field label="Native language" half>
                    <select className="adm-select" style={{ width:'100%' }} value={nativeLang} onChange={e => setNativeLang(e.target.value)}>
                      <option value="">Not specified</option>
                      {['Arabic','Farsi / Persian','French','German','Hindi','Italian','Japanese','Korean','Mandarin','Polish','Portuguese','Russian','Spanish','Turkish','Other'].map(o => <option key={o}>{o}</option>)}
                    </select>
                  </Field>
                  <Field label="Known English level" half
                    hint="Skip the placement test and set this directly">
                    <select className="adm-select" style={{ width:'100%' }} value={knownLevel} onChange={e => setKnownLevel(e.target.value)}>
                      <option value="">Run placement assessment</option>
                      {['A1 — Beginner','A2 — Elementary','B1 — Intermediate','B2 — Upper intermediate','C1 — Advanced','C2 — Proficient'].map(o => <option key={o}>{o}</option>)}
                    </select>
                  </Field>
                </div>
                <div style={{ display:'flex', flexWrap:'wrap', gap:16, marginBottom:16 }}>
                  <Field label="Primary learning goal" half>
                    <select className="adm-select" style={{ width:'100%' }} value={goal} onChange={e => setGoal(e.target.value)}>
                      <option value="">Not specified</option>
                      <option>Professional email & writing</option>
                      <option>Meetings & spoken communication</option>
                      <option>Presentations & public speaking</option>
                      <option>Job interviews</option>
                      <option>General workplace English</option>
                    </select>
                  </Field>
                  <Field label="Weekly sessions target" half>
                    <select className="adm-select" style={{ width:'100%' }} value={weeklyGoal} onChange={e => setWeeklyGoal(e.target.value)}>
                      <option value="2">2 per week</option>
                      <option value="3">3 per week</option>
                      <option value="5">5 per week (daily)</option>
                      <option value="7">7 per week (intensive)</option>
                    </select>
                  </Field>
                </div>
              </FormSection>

              {/* 4. Admin settings */}
              <FormSection title="Admin settings"
                sub="Internal settings — not visible to the student.">
                <div style={{ display:'flex', flexWrap:'wrap', gap:16, marginBottom:16 }}>
                  <Field label="Initial lifecycle stage" half>
                    <select className="adm-select" style={{ width:'100%' }} value={lifecycle} onChange={e => setLifecycle(e.target.value)}>
                      {['Onboarding required','Placement required','Course ready','Active learning'].map(o => <option key={o}>{o}</option>)}
                    </select>
                  </Field>
                  <Field label="Cohort / group tag" half hint="Optional — used for filtering">
                    <input className="adm-input" placeholder="e.g. Q3-2026 pilot"
                      value={cohort} onChange={e => setCohort(e.target.value)}/>
                  </Field>
                </div>
                <Field label="Internal notes">
                  <textarea className="adm-textarea" rows={3}
                    placeholder="Any context about this student (referral source, special requirements, etc.)…"
                    value={notes} onChange={e => setNotes(e.target.value)}/>
                </Field>
              </FormSection>

              {/* Submit */}
              <button type="submit" style={{
                width:'100%', padding:'14px', borderRadius:10, border:'none', cursor:'pointer',
                background:'linear-gradient(135deg, #FF7A59 0%, #B45CF0 52%, #5B4BE8 100%)',
                color:'#fff', fontSize:15, fontWeight:700, fontFamily:'inherit',
                boxShadow:'0 4px 16px rgba(91,75,232,.28)', transition:'opacity .15s',
              }}
              onMouseOver={e => e.currentTarget.style.opacity='.88'}
              onMouseOut={e => e.currentTarget.style.opacity='1'}>
                Create student account
              </button>
            </div>

            {/* ── RIGHT: summary panel ── */}
            <div style={{ position:'sticky', top:80 }}>
              <div className="adm-card adm-card-p" style={{ marginBottom:16 }}>
                <div style={{ fontSize:13.5, fontWeight:700, color:'var(--ink)', marginBottom:16 }}>What happens next</div>
                {[
                  { icon:'check', bg:'#E0F6EE', ic:'#13B07C', title:'Account created', sub:'Student can log in immediately with the temporary password' },
                  ...(sendEmail ? [{ icon:'mail', bg:'#EDEBFF', ic:'#5B4BE8', title:'Welcome email sent', sub:'Includes login link and onboarding instructions' }] : []),
                  ...(requireChg ? [{ icon:'key', bg:'#FFF1DC', ic:'#F0982C', title:'Password reset required', sub:'Student must set a new password before accessing the app' }] : []),
                  ...(knownLevel ? [{ icon:'target', bg:'#F2E9FF', ic:'#B45CF0', title:`CEFR set to ${knownLevel.split(' ')[0]}`, sub:'Placement assessment will be skipped' }] : [{ icon:'target', bg:'#F2E9FF', ic:'#B45CF0', title:'Placement assessment', sub:'Student will be assessed before their first lesson' }]),
                ].map((item, i) => (
                  <div key={i} style={{ display:'flex', gap:12, marginBottom:14 }}>
                    <div style={{ width:30, height:30, borderRadius:8, background:item.bg,
                      display:'grid', placeItems:'center', flexShrink:0 }}>
                      <AIcon n={item.icon} s={14} c={item.ic} w={2}/>
                    </div>
                    <div>
                      <div style={{ fontSize:13, fontWeight:700, color:'var(--ink)', lineHeight:1.3 }}>{item.title}</div>
                      <div style={{ fontSize:12, color:'var(--muted)', marginTop:2, lineHeight:1.4 }}>{item.sub}</div>
                    </div>
                  </div>
                ))}
              </div>

              {/* Cohort stats */}
              <div className="adm-card adm-card-p">
                <div style={{ fontSize:13.5, fontWeight:700, color:'var(--ink)', marginBottom:14 }}>Current cohort</div>
                {[
                  ['Total students', '8'],
                  ['Onboarded', '8 (100%)'],
                  ['Active this week', '5'],
                  ['Avg CEFR', 'B1–B2'],
                ].map(([k,v]) => (
                  <div key={k} style={{ display:'flex', justifyContent:'space-between', padding:'7px 0',
                    borderBottom:'1px solid var(--border)', fontSize:13 }}>
                    <span style={{ color:'var(--muted)' }}>{k}</span>
                    <span style={{ fontWeight:700, color:'var(--ink)' }}>{v}</span>
                  </div>
                ))}
                <div style={{ marginTop:14, padding:12, background:'#F6F4FB', borderRadius:8 }}>
                  <div style={{ fontSize:12, color:'var(--muted)', lineHeight:1.55 }}>
                    Adding this student will bring the cohort to <strong style={{ color:'var(--ink)' }}>9 students</strong>.
                  </div>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    );
  }

  window.AdminCreateStudent = AdminCreateStudent;
})();
